// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient {
    
    
    public partial class ErrorDialog {
        
        private Gtk.HBox hbox1;
        
        private Gtk.Image image1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label titleLabel;
        
        private Gtk.Label messageLabel;
        
        private Gtk.Expander expander;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView detailTextView;
        
        private Gtk.Label GtkLabel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Synapse.QtClient.ErrorDialog
            this.Name = "Synapse.QtClient.ErrorDialog";
            this.Title = Mono.Unix.Catalog.GetString("Synapse Error");
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.Resizable = false;
            this.AllowGrow = false;
            this.DefaultWidth = 300;
            this.DefaultHeight = 300;
            this.HasSeparator = false;
            // Internal child Synapse.QtClient.ErrorDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            this.hbox1.BorderWidth = ((uint)(6));
            // Container child hbox1.Gtk.Box+BoxChild
            this.image1 = new Gtk.Image();
            this.image1.Name = "image1";
            this.image1.Yalign = 0F;
            this.image1.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", Gtk.IconSize.Dialog, 48);
            this.hbox1.Add(this.image1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.image1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.titleLabel = new Gtk.Label();
            this.titleLabel.Name = "titleLabel";
            this.titleLabel.Xalign = 0F;
            this.titleLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>Primary Message</b>");
            this.titleLabel.UseMarkup = true;
            this.vbox1.Add(this.titleLabel);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.titleLabel]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.messageLabel = new Gtk.Label();
            this.messageLabel.Name = "messageLabel";
            this.messageLabel.Xalign = 0F;
            this.messageLabel.LabelProp = Mono.Unix.Catalog.GetString("Secondary Message");
            this.vbox1.Add(this.messageLabel);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.messageLabel]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.expander = new Gtk.Expander(null);
            this.expander.CanFocus = true;
            this.expander.Name = "expander";
            // Container child expander.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.detailTextView = new Gtk.TextView();
            this.detailTextView.CanFocus = true;
            this.detailTextView.Name = "detailTextView";
            this.GtkScrolledWindow.Add(this.detailTextView);
            this.expander.Add(this.GtkScrolledWindow);
            this.GtkLabel = new Gtk.Label();
            this.GtkLabel.Name = "GtkLabel";
            this.GtkLabel.LabelProp = Mono.Unix.Catalog.GetString("More Information");
            this.GtkLabel.UseUnderline = true;
            this.expander.LabelWidget = this.GtkLabel;
            this.vbox1.Add(this.expander);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.expander]));
            w7.Position = 2;
            this.hbox1.Add(this.vbox1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
            w8.Position = 1;
            w1.Add(this.hbox1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(w1[this.hbox1]));
            w9.Position = 0;
            // Internal child Synapse.QtClient.ErrorDialog.ActionArea
            Gtk.HButtonBox w10 = this.ActionArea;
            w10.Name = "dialog1_ActionArea";
            w10.Spacing = 6;
            w10.BorderWidth = ((uint)(5));
            w10.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonOk]));
            w11.Expand = false;
            w11.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.expander.Activated += new System.EventHandler(this.expander_Activated);
            this.buttonOk.Clicked += new System.EventHandler(this.OnButtonOkClicked);
        }
    }
}
