// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.Addins.Twitter {
    using System;
    using Qyoto;
    
    
    public partial class TwitterConfigurationDialog : QDialog {
        
        protected QLabel logoLabel;
        
        protected QLabel label;
        
        protected QLabel label_2;
        
        protected QLineEdit usernameLineEdit;
        
        protected QLabel label_3;
        
        protected QLineEdit passwordLineEdit;
        
        protected QDialogButtonBox buttonBox;
        
        protected void SetupUi() {
            base.ObjectName = "TwitterConfigurationDialog";
            this.WindowModality = Qt.WindowModality.NonModal;
            this.Geometry = new QRect(0, 0, 313, 137);
            this.WindowTitle = "Twitter Configuration";
            this.Modal = true;
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this);
            verticalLayout.Margin = 6;
            QHBoxLayout horizontalLayout;
            horizontalLayout = new QHBoxLayout();
            verticalLayout.AddLayout(horizontalLayout);
            this.logoLabel = new QLabel(this);
            this.logoLabel.ObjectName = "logoLabel";
            this.logoLabel.MinimumSize = new QSize(48, 0);
            this.logoLabel.Text = "";
            horizontalLayout.AddWidget(this.logoLabel);
            QVBoxLayout verticalLayout_2;
            verticalLayout_2 = new QVBoxLayout();
            horizontalLayout.AddLayout(verticalLayout_2);
            this.label = new QLabel(this);
            this.label.ObjectName = "label";
            QSizePolicy label_sizePolicy;
            label_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum);
            label_sizePolicy.SetVerticalStretch(0);
            label_sizePolicy.SetHorizontalStretch(0);
            label_sizePolicy.SetHeightForWidth(this.label.SizePolicy.HasHeightForWidth());
            this.label.SizePolicy = label_sizePolicy;
            this.label.Text = "Enter your Twitter account information:";
            verticalLayout_2.AddWidget(this.label);
            QGridLayout gridLayout_2;
            gridLayout_2 = new QGridLayout();
            verticalLayout_2.AddLayout(gridLayout_2);
            gridLayout_2.sizeConstraint = QLayout.SizeConstraint.SetMaximumSize;
            this.label_2 = new QLabel(this);
            this.label_2.ObjectName = "label_2";
            this.label_2.Text = "Username:";
            gridLayout_2.AddWidget(this.label_2, 0, 0, 1, 1);
            this.usernameLineEdit = new QLineEdit(this);
            this.usernameLineEdit.ObjectName = "usernameLineEdit";
            gridLayout_2.AddWidget(this.usernameLineEdit, 0, 1, 1, 1);
            this.label_3 = new QLabel(this);
            this.label_3.ObjectName = "label_3";
            this.label_3.Text = "Password:";
            gridLayout_2.AddWidget(this.label_3, 1, 0, 1, 1);
            this.passwordLineEdit = new QLineEdit(this);
            this.passwordLineEdit.ObjectName = "passwordLineEdit";
            this.passwordLineEdit.echoMode = QLineEdit.EchoMode.Password;
            gridLayout_2.AddWidget(this.passwordLineEdit, 1, 1, 1, 1);
            this.buttonBox = new QDialogButtonBox(this);
            this.buttonBox.ObjectName = "buttonBox";
            this.buttonBox.Orientation = Qt.Orientation.Horizontal;
            this.buttonBox.StandardButtons = (global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Cancel") | global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Ok"));
            verticalLayout.AddWidget(this.buttonBox);
            QObject.Connect(buttonBox, Qt.SIGNAL("accepted()"), this, Qt.SLOT("accept()"));
            QObject.Connect(buttonBox, Qt.SIGNAL("rejected()"), this, Qt.SLOT("reject()"));
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
