// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient.Windows {
    using System;
    using Qyoto;
    
    
    public partial class AddAccountDialog : QDialog {
        
        protected QStackedWidget stackedWidget;
        
        protected QWidget page;
        
        protected QRadioButton radioButton;
        
        protected QRadioButton radioButton_2;
        
        protected QDialogButtonBox buttonBox;
        
        protected QWidget page_2;
        
        protected QLabel label_6;
        
        protected QLabel label;
        
        protected QLineEdit jidLineEdit;
        
        protected QLabel label_2;
        
        protected QLabel label_3;
        
        protected QLineEdit passwordLineEdit;
        
        protected QLabel label_4;
        
        protected QComboBox resourceComboBox;
        
        protected QLabel label_5;
        
        protected QCheckBox autoConnectCheckBox;
        
        protected QDialogButtonBox buttonBox_2;
        
        protected void SetupUi() {
            base.ObjectName = "AddAccountDialog";
            this.Geometry = new QRect(0, 0, 436, 239);
            this.WindowTitle = "Add Account";
            this.Modal = true;
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this);
            verticalLayout.Spacing = 0;
            verticalLayout.sizeConstraint = QLayout.SizeConstraint.SetFixedSize;
            verticalLayout.Margin = 0;
            this.stackedWidget = new QStackedWidget(this);
            this.stackedWidget.ObjectName = "stackedWidget";
            this.stackedWidget.CurrentIndex = 0;
            verticalLayout.AddWidget(this.stackedWidget);
            this.page = new QWidget(this.stackedWidget);
            this.page.ObjectName = "page";
            QVBoxLayout verticalLayout_2;
            verticalLayout_2 = new QVBoxLayout(this.page);
            verticalLayout_2.Margin = 6;
            this.radioButton = new QRadioButton(this.page);
            this.radioButton.ObjectName = "radioButton";
            this.radioButton.Text = "I already have an &account I'd like to use";
            this.radioButton.Checked = true;
            verticalLayout_2.AddWidget(this.radioButton);
            this.radioButton_2 = new QRadioButton(this.page);
            this.radioButton_2.ObjectName = "radioButton_2";
            this.radioButton_2.Enabled = false;
            this.radioButton_2.Text = "I'd like to &create a new account";
            verticalLayout_2.AddWidget(this.radioButton_2);
            QSpacerItem verticalSpacer;
            verticalSpacer = new QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_2.AddItem(verticalSpacer);
            this.buttonBox = new QDialogButtonBox(this.page);
            this.buttonBox.ObjectName = "buttonBox";
            this.buttonBox.Orientation = Qt.Orientation.Horizontal;
            this.buttonBox.StandardButtons = global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Cancel");
            verticalLayout_2.AddWidget(this.buttonBox);
            this.stackedWidget.AddWidget(this.page);
            this.page_2 = new QWidget(this.stackedWidget);
            this.page_2.ObjectName = "page_2";
            QVBoxLayout verticalLayout_3;
            verticalLayout_3 = new QVBoxLayout(this.page_2);
            verticalLayout_3.Margin = 6;
            this.label_6 = new QLabel(this.page_2);
            this.label_6.ObjectName = "label_6";
            this.label_6.Text = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'DejaVu Sans'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Please enter the information about your existing account:</span></p></body></html>";
            verticalLayout_3.AddWidget(this.label_6);
            QFormLayout formLayout;
            formLayout = new QFormLayout();
            verticalLayout_3.AddLayout(formLayout);
            this.label = new QLabel(this.page_2);
            this.label.ObjectName = "label";
            this.label.Text = "&Jabber ID:";
            formLayout.SetWidget(0, QFormLayout.ItemRole.LabelRole, this.label);
            this.jidLineEdit = new QLineEdit(this.page_2);
            this.jidLineEdit.ObjectName = "jidLineEdit";
            formLayout.SetWidget(0, QFormLayout.ItemRole.FieldRole, this.jidLineEdit);
            this.label_2 = new QLabel(this.page_2);
            this.label_2.ObjectName = "label_2";
            this.label_2.Text = "Eg: username@hostname";
            this.label_2.Alignment = ((global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignLeading") | global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignLeft")) | global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignTop"));
            formLayout.SetWidget(1, QFormLayout.ItemRole.FieldRole, this.label_2);
            this.label_3 = new QLabel(this.page_2);
            this.label_3.ObjectName = "label_3";
            this.label_3.Text = "&Password:";
            formLayout.SetWidget(2, QFormLayout.ItemRole.LabelRole, this.label_3);
            this.passwordLineEdit = new QLineEdit(this.page_2);
            this.passwordLineEdit.ObjectName = "passwordLineEdit";
            this.passwordLineEdit.echoMode = QLineEdit.EchoMode.Password;
            formLayout.SetWidget(2, QFormLayout.ItemRole.FieldRole, this.passwordLineEdit);
            this.label_4 = new QLabel(this.page_2);
            this.label_4.ObjectName = "label_4";
            this.label_4.Text = "&Resource:";
            formLayout.SetWidget(3, QFormLayout.ItemRole.LabelRole, this.label_4);
            this.resourceComboBox = new QComboBox(this.page_2);
            this.resourceComboBox.ObjectName = "resourceComboBox";
            this.resourceComboBox.Editable = true;
            formLayout.SetWidget(3, QFormLayout.ItemRole.FieldRole, this.resourceComboBox);
            this.resourceComboBox.InsertItems(0, new System.Collections.Generic.List<string>(new string[] {
                            "Home",
                            "Work",
                            "Laptop",
                            "Netbook"}));
            this.label_5 = new QLabel(this.page_2);
            this.label_5.ObjectName = "label_5";
            this.label_5.Text = "One word describing this computer, i.e. \"HomeLaptop\"";
            this.label_5.Alignment = ((global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignLeading") | global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignLeft")) | global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignTop"));
            this.label_5.WordWrap = false;
            formLayout.SetWidget(4, QFormLayout.ItemRole.FieldRole, this.label_5);
            this.autoConnectCheckBox = new QCheckBox(this.page_2);
            this.autoConnectCheckBox.ObjectName = "autoConnectCheckBox";
            this.autoConnectCheckBox.Text = "Connect &Automatically";
            this.autoConnectCheckBox.Checked = true;
            formLayout.SetWidget(5, QFormLayout.ItemRole.FieldRole, this.autoConnectCheckBox);
            QSpacerItem verticalSpacer_2;
            verticalSpacer_2 = new QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_3.AddItem(verticalSpacer_2);
            this.buttonBox_2 = new QDialogButtonBox(this.page_2);
            this.buttonBox_2.ObjectName = "buttonBox_2";
            this.buttonBox_2.StandardButtons = (global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Cancel") | global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Ok"));
            verticalLayout_3.AddWidget(this.buttonBox_2);
            this.stackedWidget.AddWidget(this.page_2);
            QObject.Connect(buttonBox, Qt.SIGNAL("rejected()"), this, Qt.SLOT("reject()"));
            QObject.Connect(buttonBox_2, Qt.SIGNAL("rejected()"), this, Qt.SLOT("reject()"));
            QMetaObject.ConnectSlotsByName(this);
            this.label.SetBuddy(jidLineEdit);
            this.label_3.SetBuddy(passwordLineEdit);
            this.label_4.SetBuddy(resourceComboBox);
        }
    }
}
