// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient.Windows {
    using System;
    using Qyoto;
    
    
    public partial class AddFriendWindow : QWidget {
        
        protected QPushButton closeButton;
        
        protected QStackedWidget stackedWidget;
        
        protected QWidget page;
        
        protected QPushButton pushButton;
        
        protected QPushButton pushButton_3;
        
        protected QPushButton enterJidButton;
        
        protected QWidget page_2;
        
        protected QLabel label_2;
        
        protected QLabel label;
        
        protected QLineEdit jidLineEdit;
        
        protected QLabel label_4;
        
        protected QLineEdit nameLineEdit;
        
        protected QLabel label_3;
        
        protected Synapse.QtClient.Widgets.EditGroupsWidget groupsWidget;
        
        protected QDialogButtonBox buttonBox;
        
        protected void SetupUi() {
            base.ObjectName = "AddFriendWindow";
            this.Geometry = new QRect(0, 0, 285, 349);
            this.WindowTitle = "AddFriend";
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this);
            verticalLayout.Margin = 0;
            QHBoxLayout horizontalLayout;
            horizontalLayout = new QHBoxLayout();
            verticalLayout.AddLayout(horizontalLayout);
            QSpacerItem horizontalSpacer;
            horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum);
            horizontalLayout.AddItem(horizontalSpacer);
            this.closeButton = new QPushButton(this);
            this.closeButton.ObjectName = "closeButton";
            this.closeButton.BaseSize = new QSize(0, 0);
            this.closeButton.Text = "";
            horizontalLayout.AddWidget(this.closeButton);
            this.stackedWidget = new QStackedWidget(this);
            this.stackedWidget.ObjectName = "stackedWidget";
            this.stackedWidget.CurrentIndex = 0;
            verticalLayout.AddWidget(this.stackedWidget);
            this.page = new QWidget(this.stackedWidget);
            this.page.ObjectName = "page";
            QVBoxLayout verticalLayout_2;
            verticalLayout_2 = new QVBoxLayout(this.page);
            verticalLayout_2.Margin = 6;
            QSpacerItem verticalSpacer_2;
            verticalSpacer_2 = new QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_2.AddItem(verticalSpacer_2);
            this.pushButton = new QPushButton(this.page);
            this.pushButton.ObjectName = "pushButton";
            this.pushButton.Text = "Search && Add friends automatically...";
            verticalLayout_2.AddWidget(this.pushButton);
            this.pushButton_3 = new QPushButton(this.page);
            this.pushButton_3.ObjectName = "pushButton_3";
            this.pushButton_3.Text = "Search for friends...";
            verticalLayout_2.AddWidget(this.pushButton_3);
            this.enterJidButton = new QPushButton(this.page);
            this.enterJidButton.ObjectName = "enterJidButton";
            this.enterJidButton.Text = "Enter friend's JID...";
            verticalLayout_2.AddWidget(this.enterJidButton);
            QSpacerItem verticalSpacer;
            verticalSpacer = new QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_2.AddItem(verticalSpacer);
            this.stackedWidget.AddWidget(this.page);
            this.page_2 = new QWidget(this.stackedWidget);
            this.page_2.ObjectName = "page_2";
            QVBoxLayout verticalLayout_3;
            verticalLayout_3 = new QVBoxLayout(this.page_2);
            verticalLayout_3.Margin = 6;
            QSpacerItem verticalSpacer_3;
            verticalSpacer_3 = new QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_3.AddItem(verticalSpacer_3);
            this.label_2 = new QLabel(this.page_2);
            this.label_2.ObjectName = "label_2";
            this.label_2.Text = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'DejaVu Sans'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Add Friend</span></p></body></html>";
            verticalLayout_3.AddWidget(this.label_2);
            QGridLayout gridLayout;
            gridLayout = new QGridLayout();
            verticalLayout_3.AddLayout(gridLayout);
            this.label = new QLabel(this.page_2);
            this.label.ObjectName = "label";
            this.label.Text = "JID:";
            gridLayout.AddWidget(this.label, 0, 0, 1, 1);
            this.jidLineEdit = new QLineEdit(this.page_2);
            this.jidLineEdit.ObjectName = "jidLineEdit";
            gridLayout.AddWidget(this.jidLineEdit, 0, 1, 1, 1);
            this.label_4 = new QLabel(this.page_2);
            this.label_4.ObjectName = "label_4";
            this.label_4.Text = "Name:";
            gridLayout.AddWidget(this.label_4, 1, 0, 1, 1);
            this.nameLineEdit = new QLineEdit(this.page_2);
            this.nameLineEdit.ObjectName = "nameLineEdit";
            gridLayout.AddWidget(this.nameLineEdit, 1, 1, 1, 1);
            this.label_3 = new QLabel(this.page_2);
            this.label_3.ObjectName = "label_3";
            this.label_3.Text = "Add to Group(s):";
            verticalLayout_3.AddWidget(this.label_3);
            this.groupsWidget = new Synapse.QtClient.Widgets.EditGroupsWidget(this.page_2);
            this.groupsWidget.ObjectName = "groupsWidget";
            verticalLayout_3.AddWidget(this.groupsWidget);
            this.buttonBox = new QDialogButtonBox(this.page_2);
            this.buttonBox.ObjectName = "buttonBox";
            this.buttonBox.StandardButtons = global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "NoButton");
            verticalLayout_3.AddWidget(this.buttonBox);
            QSpacerItem verticalSpacer_4;
            verticalSpacer_4 = new QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_3.AddItem(verticalSpacer_4);
            this.stackedWidget.AddWidget(this.page_2);
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
