// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient.Windows {
    using System;
    using Qyoto;
    
    
    public partial class DebugWindow : QWidget {
        
        protected QTabWidget tabWidget;
        
        protected QWidget tab;
        
        protected QToolBox m_XmlToolBox;
        
        protected QFrame line;
        
        protected QCheckBox enableConsoleCheckBox;
        
        protected QPushButton clearConsoleButton;
        
        protected void SetupUi() {
            base.ObjectName = "DebugWindow";
            this.Geometry = new QRect(0, 0, 518, 405);
            this.WindowTitle = "DebugWindow";
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this);
            this.tabWidget = new QTabWidget(this);
            this.tabWidget.ObjectName = "tabWidget";
            this.tabWidget.CurrentIndex = 0;
            verticalLayout.AddWidget(this.tabWidget);
            this.tab = new QWidget(this.tabWidget);
            this.tab.ObjectName = "tab";
            QVBoxLayout verticalLayout_3;
            verticalLayout_3 = new QVBoxLayout(this.tab);
            verticalLayout_3.Spacing = 0;
            verticalLayout_3.Margin = 0;
            this.m_XmlToolBox = new QToolBox(this.tab);
            this.m_XmlToolBox.ObjectName = "m_XmlToolBox";
            QSizePolicy m_XmlToolBox_sizePolicy;
            m_XmlToolBox_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding);
            m_XmlToolBox_sizePolicy.SetVerticalStretch(0);
            m_XmlToolBox_sizePolicy.SetHorizontalStretch(0);
            m_XmlToolBox_sizePolicy.SetHeightForWidth(this.m_XmlToolBox.SizePolicy.HasHeightForWidth());
            this.m_XmlToolBox.SizePolicy = m_XmlToolBox_sizePolicy;
            verticalLayout_3.AddWidget(this.m_XmlToolBox);
            this.line = new QFrame(this.tab);
            this.line.ObjectName = "line";
            this.line.FrameShape = QFrame.Shape.HLine;
            this.line.FrameShadow = QFrame.Shadow.Sunken;
            verticalLayout_3.AddWidget(this.line);
            QHBoxLayout horizontalLayout;
            horizontalLayout = new QHBoxLayout();
            verticalLayout_3.AddLayout(horizontalLayout);
            horizontalLayout.sizeConstraint = QLayout.SizeConstraint.SetDefaultConstraint;
            horizontalLayout.Margin = 6;
            this.enableConsoleCheckBox = new QCheckBox(this.tab);
            this.enableConsoleCheckBox.ObjectName = "enableConsoleCheckBox";
            this.enableConsoleCheckBox.Text = "Enable";
            horizontalLayout.AddWidget(this.enableConsoleCheckBox);
            QSpacerItem horizontalSpacer;
            horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum);
            horizontalLayout.AddItem(horizontalSpacer);
            this.clearConsoleButton = new QPushButton(this.tab);
            this.clearConsoleButton.ObjectName = "clearConsoleButton";
            this.clearConsoleButton.Text = "Clear";
            horizontalLayout.AddWidget(this.clearConsoleButton);
            this.tabWidget.AddTab(this.tab, "XML Console");
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
