// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient.Widgets {
    using System;
    using Qyoto;
    
    
    public partial class EditGroupsWidget : QWidget {
        
        protected QListWidget listWidget;
        
        protected QLabel label_2;
        
        protected QLineEdit lineEdit;
        
        protected QPushButton addButton;
        
        protected void SetupUi() {
            base.ObjectName = "EditGroupsWidget";
            this.Geometry = new QRect(0, 0, 212, 239);
            this.WindowTitle = "EditGroupsWidget";
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this);
            verticalLayout.Spacing = 3;
            verticalLayout.Margin = 0;
            this.listWidget = new QListWidget(this);
            this.listWidget.ObjectName = "listWidget";
            QSizePolicy listWidget_sizePolicy;
            listWidget_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding);
            listWidget_sizePolicy.SetVerticalStretch(0);
            listWidget_sizePolicy.SetHorizontalStretch(0);
            listWidget_sizePolicy.SetHeightForWidth(this.listWidget.SizePolicy.HasHeightForWidth());
            this.listWidget.SizePolicy = listWidget_sizePolicy;
            this.listWidget.MinimumSize = new QSize(0, 50);
            this.listWidget.FrameShape = QFrame.Shape.NoFrame;
            verticalLayout.AddWidget(this.listWidget);
            QGridLayout gridLayout;
            gridLayout = new QGridLayout();
            verticalLayout.AddLayout(gridLayout);
            this.label_2 = new QLabel(this);
            this.label_2.ObjectName = "label_2";
            this.label_2.Text = "Add Group:";
            gridLayout.AddWidget(this.label_2, 0, 0, 1, 1);
            this.lineEdit = new QLineEdit(this);
            this.lineEdit.ObjectName = "lineEdit";
            gridLayout.AddWidget(this.lineEdit, 0, 1, 1, 1);
            this.addButton = new QPushButton(this);
            this.addButton.ObjectName = "addButton";
            this.addButton.Text = "";
            gridLayout.AddWidget(this.addButton, 0, 2, 1, 1);
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
