// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using Qyoto;


public partial class EditGroupsWindow : QWidget {
    
    protected QLabel label;
    
    protected QListWidget listWidget;
    
    protected QDialogButtonBox buttonBox;
    
    protected void SetupUi() {
        base.ObjectName = "EditGroupsWindow";
        this.Geometry = new QRect(0, 0, 250, 344);
        this.WindowTitle = "EditGroupsWindow";
        QVBoxLayout verticalLayout;
        verticalLayout = new QVBoxLayout(this);
        QSpacerItem verticalSpacer;
        verticalSpacer = new QSpacerItem(20, 40, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum);
        verticalLayout.AddItem(verticalSpacer);
        this.label = new QLabel(this);
        this.label.ObjectName = "label";
        QSizePolicy label_sizePolicy;
        label_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum);
        label_sizePolicy.SetVerticalStretch(0);
        label_sizePolicy.SetHorizontalStretch(0);
        label_sizePolicy.SetHeightForWidth(this.label.SizePolicy.HasHeightForWidth());
        this.label.SizePolicy = label_sizePolicy;
        this.label.Text = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'DejaVu Sans'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Edit Groups</span></p>\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><span style=\" font-weight:400;\">eric@extremeboredom.net</span></p></body></html>";
        verticalLayout.AddWidget(this.label);
        this.listWidget = new QListWidget(this);
        this.listWidget.ObjectName = "listWidget";
        QSizePolicy listWidget_sizePolicy;
        listWidget_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum);
        listWidget_sizePolicy.SetVerticalStretch(0);
        listWidget_sizePolicy.SetHorizontalStretch(0);
        listWidget_sizePolicy.SetHeightForWidth(this.listWidget.SizePolicy.HasHeightForWidth());
        this.listWidget.SizePolicy = listWidget_sizePolicy;
        this.listWidget.MinimumSize = new QSize(0, 50);
        this.listWidget.FrameShape = QFrame.Shape.NoFrame;
        verticalLayout.AddWidget(this.listWidget);
        this.buttonBox = new QDialogButtonBox(this);
        this.buttonBox.ObjectName = "buttonBox";
        verticalLayout.AddWidget(this.buttonBox);
        QSpacerItem verticalSpacer_2;
        verticalSpacer_2 = new QSpacerItem(20, 40, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum);
        verticalLayout.AddItem(verticalSpacer_2);
        QMetaObject.ConnectSlotsByName(this);
    }
}
