// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient.Windows {
    using System;
    using Qyoto;
    
    
    public partial class EditProfileDialog : QDialog {
        
        protected QTabWidget mainTabWidget;
        
        protected QWidget tab;
        
        protected QWidget widget;
        
        protected QGroupBox groupBox_2;
        
        protected QLabel label_9;
        
        protected QLineEdit fullNameLineEdit;
        
        protected QLabel label_10;
        
        protected QLineEdit nicknameLineEdit;
        
        protected QLabel label_14;
        
        protected QDateEdit birthdayDateEdit;
        
        protected QLabel label_11;
        
        protected QLineEdit websiteLineEdit;
        
        protected QGroupBox groupBox_5;
        
        protected QTextEdit bioTextEdit;
        
        protected QGroupBox groupBox_4;
        
        protected QLabel label_12;
        
        protected QLineEdit lineEdit_9;
        
        protected QLabel label_13;
        
        protected QLineEdit lineEdit_11;
        
        protected QLabel label_15;
        
        protected QLineEdit lineEdit_12;
        
        protected QLabel label_16;
        
        protected QLineEdit lineEdit_13;
        
        protected QLabel label_23;
        
        protected QLineEdit lineEdit_21;
        
        protected QLabel label_17;
        
        protected QLineEdit lineEdit_14;
        
        protected QLabel label_18;
        
        protected QLineEdit lineEdit_15;
        
        protected QWidget tab_4;
        
        protected QGroupBox groupBox_6;
        
        protected QLabel label;
        
        protected QLineEdit workCompanyLineEdit;
        
        protected QLabel label_6;
        
        protected QLineEdit workDepartmentLineEdit;
        
        protected QLabel label_7;
        
        protected QLineEdit workPositionLineEdit;
        
        protected QGroupBox groupBox;
        
        protected QLabel label_8;
        
        protected QLineEdit workEmailLineEdit;
        
        protected QLabel label_21;
        
        protected QLineEdit workAddressLineEdit;
        
        protected QLabel label_19;
        
        protected QLineEdit workCityLineEdit;
        
        protected QLabel label_24;
        
        protected QLineEdit workStateLineEdit;
        
        protected QLabel label_20;
        
        protected QLineEdit workZipLineEdit;
        
        protected QLabel label_22;
        
        protected QLineEdit workCountryLineEdit;
        
        protected QLabel label_2;
        
        protected QLineEdit workPhoneLineEdit;
        
        protected QWidget tab_2;
        
        protected QLabel label_4;
        
        protected QLabel avatarLabel;
        
        protected QPushButton avatarBrowseButton;
        
        protected QPushButton clearAvatarButton;
        
        protected QFrame line_2;
        
        protected QLabel label_5;
        
        protected QLineEdit avatarSearchLineEdit;
        
        protected QPushButton avatarSearchButton;
        
        protected QTabWidget avatarTabWidget;
        
        protected QWidget tab_3;
        
        protected QScrollArea scrollArea;
        
        protected QWidget webIdentitiesContainer;
        
        protected QDialogButtonBox buttonBox;
        
        protected void SetupUi() {
            base.ObjectName = "EditProfileDialog";
            this.Geometry = new QRect(0, 0, 605, 459);
            this.WindowTitle = "Edit Profile";
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this);
            verticalLayout.Margin = 6;
            this.mainTabWidget = new QTabWidget(this);
            this.mainTabWidget.ObjectName = "mainTabWidget";
            this.mainTabWidget.CurrentIndex = 0;
            verticalLayout.AddWidget(this.mainTabWidget);
            this.tab = new QWidget(this.mainTabWidget);
            this.tab.ObjectName = "tab";
            this.tab.Enabled = false;
            QHBoxLayout horizontalLayout;
            horizontalLayout = new QHBoxLayout(this.tab);
            horizontalLayout.Margin = 6;
            this.widget = new QWidget(this.tab);
            this.widget.ObjectName = "widget";
            QSizePolicy widget_sizePolicy;
            widget_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred);
            widget_sizePolicy.SetVerticalStretch(0);
            widget_sizePolicy.SetHorizontalStretch(0);
            widget_sizePolicy.SetHeightForWidth(this.widget.SizePolicy.HasHeightForWidth());
            this.widget.SizePolicy = widget_sizePolicy;
            QVBoxLayout verticalLayout_2;
            verticalLayout_2 = new QVBoxLayout(this.widget);
            verticalLayout_2.Margin = 0;
            this.groupBox_2 = new QGroupBox(this.widget);
            this.groupBox_2.ObjectName = "groupBox_2";
            QSizePolicy groupBox_2_sizePolicy;
            groupBox_2_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred);
            groupBox_2_sizePolicy.SetVerticalStretch(0);
            groupBox_2_sizePolicy.SetHorizontalStretch(0);
            groupBox_2_sizePolicy.SetHeightForWidth(this.groupBox_2.SizePolicy.HasHeightForWidth());
            this.groupBox_2.SizePolicy = groupBox_2_sizePolicy;
            this.groupBox_2.Title = "Basic Information";
            QFormLayout formLayout_2;
            formLayout_2 = new QFormLayout(this.groupBox_2);
            formLayout_2.fieldGrowthPolicy = QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow;
            formLayout_2.SetContentsMargins(6, 12, 6, 0);
            this.label_9 = new QLabel(this.groupBox_2);
            this.label_9.ObjectName = "label_9";
            this.label_9.Text = "Full Name:";
            formLayout_2.SetWidget(0, QFormLayout.ItemRole.LabelRole, this.label_9);
            this.fullNameLineEdit = new QLineEdit(this.groupBox_2);
            this.fullNameLineEdit.ObjectName = "fullNameLineEdit";
            formLayout_2.SetWidget(0, QFormLayout.ItemRole.FieldRole, this.fullNameLineEdit);
            this.label_10 = new QLabel(this.groupBox_2);
            this.label_10.ObjectName = "label_10";
            this.label_10.Text = "Nickname:";
            formLayout_2.SetWidget(1, QFormLayout.ItemRole.LabelRole, this.label_10);
            this.nicknameLineEdit = new QLineEdit(this.groupBox_2);
            this.nicknameLineEdit.ObjectName = "nicknameLineEdit";
            formLayout_2.SetWidget(1, QFormLayout.ItemRole.FieldRole, this.nicknameLineEdit);
            this.label_14 = new QLabel(this.groupBox_2);
            this.label_14.ObjectName = "label_14";
            this.label_14.Text = "Birthday:";
            formLayout_2.SetWidget(2, QFormLayout.ItemRole.LabelRole, this.label_14);
            this.birthdayDateEdit = new QDateEdit(this.groupBox_2);
            this.birthdayDateEdit.ObjectName = "birthdayDateEdit";
            this.birthdayDateEdit.DisplayFormat = "M/d/yyyy";
            this.birthdayDateEdit.CalendarPopup = true;
            formLayout_2.SetWidget(2, QFormLayout.ItemRole.FieldRole, this.birthdayDateEdit);
            this.label_11 = new QLabel(this.groupBox_2);
            this.label_11.ObjectName = "label_11";
            this.label_11.Text = "Website:";
            formLayout_2.SetWidget(3, QFormLayout.ItemRole.LabelRole, this.label_11);
            this.websiteLineEdit = new QLineEdit(this.groupBox_2);
            this.websiteLineEdit.ObjectName = "websiteLineEdit";
            formLayout_2.SetWidget(3, QFormLayout.ItemRole.FieldRole, this.websiteLineEdit);
            verticalLayout_2.AddWidget(this.groupBox_2);
            this.groupBox_5 = new QGroupBox(this.widget);
            this.groupBox_5.ObjectName = "groupBox_5";
            this.groupBox_5.Title = "About Me";
            this.groupBox_5.Flat = false;
            this.groupBox_5.Checkable = false;
            QHBoxLayout horizontalLayout_3;
            horizontalLayout_3 = new QHBoxLayout(this.groupBox_5);
            horizontalLayout_3.SetContentsMargins(6, 12, 6, 6);
            this.bioTextEdit = new QTextEdit(this.groupBox_5);
            this.bioTextEdit.ObjectName = "bioTextEdit";
            horizontalLayout_3.AddWidget(this.bioTextEdit);
            verticalLayout_2.AddWidget(this.groupBox_5);
            horizontalLayout.AddWidget(this.widget);
            this.groupBox_4 = new QGroupBox(this.tab);
            this.groupBox_4.ObjectName = "groupBox_4";
            QSizePolicy groupBox_4_sizePolicy;
            groupBox_4_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred);
            groupBox_4_sizePolicy.SetVerticalStretch(0);
            groupBox_4_sizePolicy.SetHorizontalStretch(0);
            groupBox_4_sizePolicy.SetHeightForWidth(this.groupBox_4.SizePolicy.HasHeightForWidth());
            this.groupBox_4.SizePolicy = groupBox_4_sizePolicy;
            this.groupBox_4.Title = "Contact Information";
            QFormLayout formLayout_3;
            formLayout_3 = new QFormLayout(this.groupBox_4);
            formLayout_3.SetContentsMargins(6, 12, 6, 6);
            this.label_12 = new QLabel(this.groupBox_4);
            this.label_12.ObjectName = "label_12";
            this.label_12.Text = "Email:";
            formLayout_3.SetWidget(0, QFormLayout.ItemRole.LabelRole, this.label_12);
            this.lineEdit_9 = new QLineEdit(this.groupBox_4);
            this.lineEdit_9.ObjectName = "lineEdit_9";
            formLayout_3.SetWidget(0, QFormLayout.ItemRole.FieldRole, this.lineEdit_9);
            this.label_13 = new QLabel(this.groupBox_4);
            this.label_13.ObjectName = "label_13";
            this.label_13.Text = "Phone:";
            formLayout_3.SetWidget(1, QFormLayout.ItemRole.LabelRole, this.label_13);
            this.lineEdit_11 = new QLineEdit(this.groupBox_4);
            this.lineEdit_11.ObjectName = "lineEdit_11";
            formLayout_3.SetWidget(1, QFormLayout.ItemRole.FieldRole, this.lineEdit_11);
            this.label_15 = new QLabel(this.groupBox_4);
            this.label_15.ObjectName = "label_15";
            this.label_15.Text = "Address:";
            formLayout_3.SetWidget(2, QFormLayout.ItemRole.LabelRole, this.label_15);
            this.lineEdit_12 = new QLineEdit(this.groupBox_4);
            this.lineEdit_12.ObjectName = "lineEdit_12";
            formLayout_3.SetWidget(2, QFormLayout.ItemRole.FieldRole, this.lineEdit_12);
            this.label_16 = new QLabel(this.groupBox_4);
            this.label_16.ObjectName = "label_16";
            this.label_16.Text = "City/Town:";
            formLayout_3.SetWidget(3, QFormLayout.ItemRole.LabelRole, this.label_16);
            this.lineEdit_13 = new QLineEdit(this.groupBox_4);
            this.lineEdit_13.ObjectName = "lineEdit_13";
            formLayout_3.SetWidget(3, QFormLayout.ItemRole.FieldRole, this.lineEdit_13);
            this.label_23 = new QLabel(this.groupBox_4);
            this.label_23.ObjectName = "label_23";
            this.label_23.Text = "State:";
            formLayout_3.SetWidget(4, QFormLayout.ItemRole.LabelRole, this.label_23);
            this.lineEdit_21 = new QLineEdit(this.groupBox_4);
            this.lineEdit_21.ObjectName = "lineEdit_21";
            formLayout_3.SetWidget(4, QFormLayout.ItemRole.FieldRole, this.lineEdit_21);
            this.label_17 = new QLabel(this.groupBox_4);
            this.label_17.ObjectName = "label_17";
            this.label_17.Text = "Zip:";
            formLayout_3.SetWidget(5, QFormLayout.ItemRole.LabelRole, this.label_17);
            this.lineEdit_14 = new QLineEdit(this.groupBox_4);
            this.lineEdit_14.ObjectName = "lineEdit_14";
            formLayout_3.SetWidget(5, QFormLayout.ItemRole.FieldRole, this.lineEdit_14);
            this.label_18 = new QLabel(this.groupBox_4);
            this.label_18.ObjectName = "label_18";
            this.label_18.Text = "Country:";
            formLayout_3.SetWidget(6, QFormLayout.ItemRole.LabelRole, this.label_18);
            this.lineEdit_15 = new QLineEdit(this.groupBox_4);
            this.lineEdit_15.ObjectName = "lineEdit_15";
            formLayout_3.SetWidget(6, QFormLayout.ItemRole.FieldRole, this.lineEdit_15);
            horizontalLayout.AddWidget(this.groupBox_4);
            this.mainTabWidget.AddTab(this.tab, "Personal Information");
            this.tab_4 = new QWidget(this.mainTabWidget);
            this.tab_4.ObjectName = "tab_4";
            this.tab_4.Enabled = false;
            QHBoxLayout horizontalLayout_5;
            horizontalLayout_5 = new QHBoxLayout(this.tab_4);
            horizontalLayout_5.Margin = 6;
            this.groupBox_6 = new QGroupBox(this.tab_4);
            this.groupBox_6.ObjectName = "groupBox_6";
            QSizePolicy groupBox_6_sizePolicy;
            groupBox_6_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred);
            groupBox_6_sizePolicy.SetVerticalStretch(0);
            groupBox_6_sizePolicy.SetHorizontalStretch(0);
            groupBox_6_sizePolicy.SetHeightForWidth(this.groupBox_6.SizePolicy.HasHeightForWidth());
            this.groupBox_6.SizePolicy = groupBox_6_sizePolicy;
            this.groupBox_6.Title = "Company Information";
            QFormLayout formLayout_4;
            formLayout_4 = new QFormLayout(this.groupBox_6);
            formLayout_4.SetContentsMargins(6, 12, 6, 0);
            this.label = new QLabel(this.groupBox_6);
            this.label.ObjectName = "label";
            this.label.Text = "Company:";
            formLayout_4.SetWidget(0, QFormLayout.ItemRole.LabelRole, this.label);
            this.workCompanyLineEdit = new QLineEdit(this.groupBox_6);
            this.workCompanyLineEdit.ObjectName = "workCompanyLineEdit";
            formLayout_4.SetWidget(0, QFormLayout.ItemRole.FieldRole, this.workCompanyLineEdit);
            this.label_6 = new QLabel(this.groupBox_6);
            this.label_6.ObjectName = "label_6";
            this.label_6.Text = "Department:";
            formLayout_4.SetWidget(1, QFormLayout.ItemRole.LabelRole, this.label_6);
            this.workDepartmentLineEdit = new QLineEdit(this.groupBox_6);
            this.workDepartmentLineEdit.ObjectName = "workDepartmentLineEdit";
            formLayout_4.SetWidget(1, QFormLayout.ItemRole.FieldRole, this.workDepartmentLineEdit);
            this.label_7 = new QLabel(this.groupBox_6);
            this.label_7.ObjectName = "label_7";
            this.label_7.Text = "Position:";
            formLayout_4.SetWidget(2, QFormLayout.ItemRole.LabelRole, this.label_7);
            this.workPositionLineEdit = new QLineEdit(this.groupBox_6);
            this.workPositionLineEdit.ObjectName = "workPositionLineEdit";
            formLayout_4.SetWidget(2, QFormLayout.ItemRole.FieldRole, this.workPositionLineEdit);
            horizontalLayout_5.AddWidget(this.groupBox_6);
            this.groupBox = new QGroupBox(this.tab_4);
            this.groupBox.ObjectName = "groupBox";
            QSizePolicy groupBox_sizePolicy;
            groupBox_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred);
            groupBox_sizePolicy.SetVerticalStretch(0);
            groupBox_sizePolicy.SetHorizontalStretch(0);
            groupBox_sizePolicy.SetHeightForWidth(this.groupBox.SizePolicy.HasHeightForWidth());
            this.groupBox.SizePolicy = groupBox_sizePolicy;
            this.groupBox.Title = "Contact Information";
            QFormLayout formLayout;
            formLayout = new QFormLayout(this.groupBox);
            formLayout.fieldGrowthPolicy = QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow;
            formLayout.SetContentsMargins(6, 12, 6, 0);
            this.label_8 = new QLabel(this.groupBox);
            this.label_8.ObjectName = "label_8";
            this.label_8.Text = "Email:";
            formLayout.SetWidget(0, QFormLayout.ItemRole.LabelRole, this.label_8);
            this.workEmailLineEdit = new QLineEdit(this.groupBox);
            this.workEmailLineEdit.ObjectName = "workEmailLineEdit";
            formLayout.SetWidget(0, QFormLayout.ItemRole.FieldRole, this.workEmailLineEdit);
            this.label_21 = new QLabel(this.groupBox);
            this.label_21.ObjectName = "label_21";
            this.label_21.Text = "Address:";
            formLayout.SetWidget(2, QFormLayout.ItemRole.LabelRole, this.label_21);
            this.workAddressLineEdit = new QLineEdit(this.groupBox);
            this.workAddressLineEdit.ObjectName = "workAddressLineEdit";
            formLayout.SetWidget(2, QFormLayout.ItemRole.FieldRole, this.workAddressLineEdit);
            this.label_19 = new QLabel(this.groupBox);
            this.label_19.ObjectName = "label_19";
            this.label_19.Text = "City/Town:";
            formLayout.SetWidget(3, QFormLayout.ItemRole.LabelRole, this.label_19);
            this.workCityLineEdit = new QLineEdit(this.groupBox);
            this.workCityLineEdit.ObjectName = "workCityLineEdit";
            formLayout.SetWidget(3, QFormLayout.ItemRole.FieldRole, this.workCityLineEdit);
            this.label_24 = new QLabel(this.groupBox);
            this.label_24.ObjectName = "label_24";
            this.label_24.Text = "State:";
            formLayout.SetWidget(4, QFormLayout.ItemRole.LabelRole, this.label_24);
            this.workStateLineEdit = new QLineEdit(this.groupBox);
            this.workStateLineEdit.ObjectName = "workStateLineEdit";
            formLayout.SetWidget(4, QFormLayout.ItemRole.FieldRole, this.workStateLineEdit);
            this.label_20 = new QLabel(this.groupBox);
            this.label_20.ObjectName = "label_20";
            this.label_20.Text = "Zip:";
            formLayout.SetWidget(5, QFormLayout.ItemRole.LabelRole, this.label_20);
            this.workZipLineEdit = new QLineEdit(this.groupBox);
            this.workZipLineEdit.ObjectName = "workZipLineEdit";
            formLayout.SetWidget(5, QFormLayout.ItemRole.FieldRole, this.workZipLineEdit);
            this.label_22 = new QLabel(this.groupBox);
            this.label_22.ObjectName = "label_22";
            this.label_22.Text = "Country:";
            formLayout.SetWidget(6, QFormLayout.ItemRole.LabelRole, this.label_22);
            this.workCountryLineEdit = new QLineEdit(this.groupBox);
            this.workCountryLineEdit.ObjectName = "workCountryLineEdit";
            formLayout.SetWidget(6, QFormLayout.ItemRole.FieldRole, this.workCountryLineEdit);
            this.label_2 = new QLabel(this.groupBox);
            this.label_2.ObjectName = "label_2";
            this.label_2.Text = "Phone:";
            formLayout.SetWidget(1, QFormLayout.ItemRole.LabelRole, this.label_2);
            this.workPhoneLineEdit = new QLineEdit(this.groupBox);
            this.workPhoneLineEdit.ObjectName = "workPhoneLineEdit";
            formLayout.SetWidget(1, QFormLayout.ItemRole.FieldRole, this.workPhoneLineEdit);
            horizontalLayout_5.AddWidget(this.groupBox);
            this.mainTabWidget.AddTab(this.tab_4, "Work Information");
            this.tab_2 = new QWidget(this.mainTabWidget);
            this.tab_2.ObjectName = "tab_2";
            QHBoxLayout horizontalLayout_2;
            horizontalLayout_2 = new QHBoxLayout(this.tab_2);
            horizontalLayout_2.Margin = 6;
            QVBoxLayout verticalLayout_4;
            verticalLayout_4 = new QVBoxLayout();
            horizontalLayout_2.AddLayout(verticalLayout_4);
            verticalLayout_4.sizeConstraint = QLayout.SizeConstraint.SetMinimumSize;
            this.label_4 = new QLabel(this.tab_2);
            this.label_4.ObjectName = "label_4";
            this.label_4.Text = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Bitstream Vera Sans'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Your Avatar:</span></p></body></html>";
            verticalLayout_4.AddWidget(this.label_4);
            this.avatarLabel = new QLabel(this.tab_2);
            this.avatarLabel.ObjectName = "avatarLabel";
            this.avatarLabel.MinimumSize = new QSize(48, 96);
            this.avatarLabel.FrameShape = QFrame.Shape.StyledPanel;
            this.avatarLabel.FrameShadow = QFrame.Shadow.Raised;
            this.avatarLabel.Text = "";
            this.avatarLabel.Alignment = global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignCenter");
            verticalLayout_4.AddWidget(this.avatarLabel);
            this.avatarBrowseButton = new QPushButton(this.tab_2);
            this.avatarBrowseButton.ObjectName = "avatarBrowseButton";
            this.avatarBrowseButton.Text = "Select File...";
            verticalLayout_4.AddWidget(this.avatarBrowseButton);
            this.clearAvatarButton = new QPushButton(this.tab_2);
            this.clearAvatarButton.ObjectName = "clearAvatarButton";
            this.clearAvatarButton.Text = "Clear";
            verticalLayout_4.AddWidget(this.clearAvatarButton);
            QSpacerItem verticalSpacer;
            verticalSpacer = new QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_4.AddItem(verticalSpacer);
            this.line_2 = new QFrame(this.tab_2);
            this.line_2.ObjectName = "line_2";
            this.line_2.FrameShape = QFrame.Shape.VLine;
            this.line_2.FrameShadow = QFrame.Shadow.Sunken;
            horizontalLayout_2.AddWidget(this.line_2);
            QVBoxLayout verticalLayout_5;
            verticalLayout_5 = new QVBoxLayout();
            horizontalLayout_2.AddLayout(verticalLayout_5);
            QGridLayout gridLayout_2;
            gridLayout_2 = new QGridLayout();
            verticalLayout_5.AddLayout(gridLayout_2);
            this.label_5 = new QLabel(this.tab_2);
            this.label_5.ObjectName = "label_5";
            this.label_5.Text = "Search:";
            this.label_5.SetBuddy(avatarSearchLineEdit);
            gridLayout_2.AddWidget(this.label_5, 0, 0, 1, 1);
            this.avatarSearchLineEdit = new QLineEdit(this.tab_2);
            this.avatarSearchLineEdit.ObjectName = "avatarSearchLineEdit";
            gridLayout_2.AddWidget(this.avatarSearchLineEdit, 0, 1, 1, 1);
            this.avatarSearchButton = new QPushButton(this.tab_2);
            this.avatarSearchButton.ObjectName = "avatarSearchButton";
            this.avatarSearchButton.Text = "Search";
            this.avatarSearchButton.Default = true;
            gridLayout_2.AddWidget(this.avatarSearchButton, 0, 2, 1, 1);
            this.avatarTabWidget = new QTabWidget(this.tab_2);
            this.avatarTabWidget.ObjectName = "avatarTabWidget";
            this.avatarTabWidget.CurrentIndex = -1;
            verticalLayout_5.AddWidget(this.avatarTabWidget);
            this.mainTabWidget.AddTab(this.tab_2, "Avatar");
            this.tab_3 = new QWidget(this.mainTabWidget);
            this.tab_3.ObjectName = "tab_3";
            QVBoxLayout verticalLayout_3;
            verticalLayout_3 = new QVBoxLayout(this.tab_3);
            verticalLayout_3.Margin = 0;
            this.scrollArea = new QScrollArea(this.tab_3);
            this.scrollArea.ObjectName = "scrollArea";
            this.scrollArea.StyleSheet = "background: palette(base);";
            this.scrollArea.FrameShape = QFrame.Shape.NoFrame;
            this.scrollArea.HorizontalScrollBarPolicy = Qt.ScrollBarPolicy.ScrollBarAlwaysOff;
            this.scrollArea.WidgetResizable = true;
            this.scrollArea.Alignment = ((global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignLeading") | global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignLeft")) | global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignTop"));
            verticalLayout_3.AddWidget(this.scrollArea);
            this.webIdentitiesContainer = new QWidget(this.scrollArea);
            this.webIdentitiesContainer.ObjectName = "webIdentitiesContainer";
            this.webIdentitiesContainer.Geometry = new QRect(0, 0, 589, 376);
            QVBoxLayout verticalLayout_6;
            verticalLayout_6 = new QVBoxLayout(this.webIdentitiesContainer);
            verticalLayout_6.Margin = 6;
            QSpacerItem verticalSpacer_2;
            verticalSpacer_2 = new QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_6.AddItem(verticalSpacer_2);
            this.scrollArea.SetWidget(this.webIdentitiesContainer);
            this.mainTabWidget.AddTab(this.tab_3, "Web Identities");
            this.buttonBox = new QDialogButtonBox(this);
            this.buttonBox.ObjectName = "buttonBox";
            this.buttonBox.StandardButtons = (global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Cancel") | global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Ok"));
            verticalLayout.AddWidget(this.buttonBox);
            QObject.Connect(buttonBox, Qt.SIGNAL("rejected()"), this, Qt.SLOT("reject()"));
            QObject.Connect(buttonBox, Qt.SIGNAL("accepted()"), this, Qt.SLOT("accept()"));
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
