// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient.Windows {
    using System;
    using Qyoto;
    
    
    public partial class InviteToMucDialog : QDialog {
        
        protected QStackedWidget stackedWidget;
        
        protected QWidget page;
        
        protected QLabel label;
        
        protected QListWidget mucsListWidget;
        
        protected QWidget page_2;
        
        protected QTabWidget tabWidget;
        
        protected QWidget tab;
        
        protected QLabel label_3;
        
        protected QListWidget friendsListWidget;
        
        protected QWidget tab_2;
        
        protected QLabel label_2;
        
        protected QLineEdit urlLineEdit;
        
        protected QPushButton emailButton;
        
        protected QPushButton copyButton;
        
        protected QDialogButtonBox buttonBox;
        
        protected void SetupUi() {
            base.ObjectName = "InviteToMucDialog";
            this.Geometry = new QRect(0, 0, 402, 289);
            this.WindowTitle = "Invite to Conference";
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this);
            verticalLayout.Margin = 6;
            this.stackedWidget = new QStackedWidget(this);
            this.stackedWidget.ObjectName = "stackedWidget";
            this.stackedWidget.CurrentIndex = 0;
            verticalLayout.AddWidget(this.stackedWidget);
            this.page = new QWidget(this.stackedWidget);
            this.page.ObjectName = "page";
            QVBoxLayout verticalLayout_2;
            verticalLayout_2 = new QVBoxLayout(this.page);
            verticalLayout_2.Margin = 0;
            this.label = new QLabel(this.page);
            this.label.ObjectName = "label";
            this.label.Text = "Select Conference:";
            verticalLayout_2.AddWidget(this.label);
            this.mucsListWidget = new QListWidget(this.page);
            this.mucsListWidget.ObjectName = "mucsListWidget";
            this.mucsListWidget.selectionBehavior = QAbstractItemView.SelectionBehavior.SelectRows;
            verticalLayout_2.AddWidget(this.mucsListWidget);
            this.stackedWidget.AddWidget(this.page);
            this.page_2 = new QWidget(this.stackedWidget);
            this.page_2.ObjectName = "page_2";
            QVBoxLayout verticalLayout_3;
            verticalLayout_3 = new QVBoxLayout(this.page_2);
            verticalLayout_3.Margin = 0;
            this.tabWidget = new QTabWidget(this.page_2);
            this.tabWidget.ObjectName = "tabWidget";
            this.tabWidget.CurrentIndex = 0;
            verticalLayout_3.AddWidget(this.tabWidget);
            this.tab = new QWidget(this.tabWidget);
            this.tab.ObjectName = "tab";
            QVBoxLayout verticalLayout_5;
            verticalLayout_5 = new QVBoxLayout(this.tab);
            verticalLayout_5.Margin = 6;
            this.label_3 = new QLabel(this.tab);
            this.label_3.ObjectName = "label_3";
            this.label_3.Text = "Select friends to invite:";
            verticalLayout_5.AddWidget(this.label_3);
            this.friendsListWidget = new QListWidget(this.tab);
            this.friendsListWidget.ObjectName = "friendsListWidget";
            verticalLayout_5.AddWidget(this.friendsListWidget);
            this.tabWidget.AddTab(this.tab, "Invite Friends");
            this.tab_2 = new QWidget(this.tabWidget);
            this.tab_2.ObjectName = "tab_2";
            QVBoxLayout verticalLayout_4;
            verticalLayout_4 = new QVBoxLayout(this.tab_2);
            verticalLayout_4.SetContentsMargins(6, 6, 6, 0);
            this.label_2 = new QLabel(this.tab_2);
            this.label_2.ObjectName = "label_2";
            this.label_2.Text = "Send this URL to anybody:";
            verticalLayout_4.AddWidget(this.label_2);
            this.urlLineEdit = new QLineEdit(this.tab_2);
            this.urlLineEdit.ObjectName = "urlLineEdit";
            this.urlLineEdit.ReadOnly = true;
            verticalLayout_4.AddWidget(this.urlLineEdit);
            QHBoxLayout horizontalLayout;
            horizontalLayout = new QHBoxLayout();
            verticalLayout_4.AddLayout(horizontalLayout);
            this.emailButton = new QPushButton(this.tab_2);
            this.emailButton.ObjectName = "emailButton";
            this.emailButton.Text = "&Email";
            horizontalLayout.AddWidget(this.emailButton);
            this.copyButton = new QPushButton(this.tab_2);
            this.copyButton.ObjectName = "copyButton";
            this.copyButton.Text = "&Copy";
            horizontalLayout.AddWidget(this.copyButton);
            QSpacerItem horizontalSpacer;
            horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum);
            horizontalLayout.AddItem(horizontalSpacer);
            QSpacerItem verticalSpacer;
            verticalSpacer = new QSpacerItem(20, 99, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding);
            verticalLayout_4.AddItem(verticalSpacer);
            this.tabWidget.AddTab(this.tab_2, "Invite Anyone");
            this.stackedWidget.AddWidget(this.page_2);
            this.buttonBox = new QDialogButtonBox(this);
            this.buttonBox.ObjectName = "buttonBox";
            this.buttonBox.Orientation = Qt.Orientation.Horizontal;
            this.buttonBox.StandardButtons = ((global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Cancel") | global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Close")) | global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Ok"));
            verticalLayout.AddWidget(this.buttonBox);
            QObject.Connect(buttonBox, Qt.SIGNAL("accepted()"), this, Qt.SLOT("accept()"));
            QObject.Connect(buttonBox, Qt.SIGNAL("rejected()"), this, Qt.SLOT("reject()"));
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
