// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient.Windows {
    using System;
    using Qyoto;
    
    
    public partial class MucAffiliationDialog : QDialog {
        
        protected QLabel roomLabel;
        
        protected QLabel label_2;
        
        protected QLabel label_3;
        
        protected QLabel userLabel;
        
        protected QRadioButton ownerRadioButton;
        
        protected QRadioButton adminRadioButton;
        
        protected QRadioButton memberRadioButton;
        
        protected QRadioButton outcastRadioButton;
        
        protected QRadioButton noneRadioButton;
        
        protected QLineEdit reasonLineEdit;
        
        protected QLabel label;
        
        protected QLabel label_4;
        
        protected QDialogButtonBox buttonBox;
        
        protected void SetupUi() {
            base.ObjectName = "MucAffiliationDialog";
            this.Geometry = new QRect(0, 0, 336, 245);
            this.WindowTitle = "Change Participant Affiliation";
            QVBoxLayout verticalLayout_2;
            verticalLayout_2 = new QVBoxLayout(this);
            verticalLayout_2.sizeConstraint = QLayout.SizeConstraint.SetFixedSize;
            verticalLayout_2.Margin = 6;
            QGridLayout gridLayout;
            gridLayout = new QGridLayout();
            verticalLayout_2.AddLayout(gridLayout);
            this.roomLabel = new QLabel(this);
            this.roomLabel.ObjectName = "roomLabel";
            this.roomLabel.Text = "synapse@conference.extremeboredom.net";
            gridLayout.AddWidget(this.roomLabel, 0, 1, 1, 1);
            this.label_2 = new QLabel(this);
            this.label_2.ObjectName = "label_2";
            this.label_2.Text = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Bitstream Vera Sans'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Room:</span></p></body></html>";
            gridLayout.AddWidget(this.label_2, 0, 0, 1, 1);
            this.label_3 = new QLabel(this);
            this.label_3.ObjectName = "label_3";
            this.label_3.Text = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Bitstream Vera Sans'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">User:</span></p></body></html>";
            gridLayout.AddWidget(this.label_3, 1, 0, 1, 1);
            this.userLabel = new QLabel(this);
            this.userLabel.ObjectName = "userLabel";
            this.userLabel.Text = "eric@extremeboredom.net";
            gridLayout.AddWidget(this.userLabel, 1, 1, 1, 1);
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout();
            verticalLayout_2.AddLayout(verticalLayout);
            verticalLayout.Spacing = 0;
            verticalLayout.Margin = 0;
            this.ownerRadioButton = new QRadioButton(this);
            this.ownerRadioButton.ObjectName = "ownerRadioButton";
            this.ownerRadioButton.Text = "Owner";
            verticalLayout.AddWidget(this.ownerRadioButton);
            this.adminRadioButton = new QRadioButton(this);
            this.adminRadioButton.ObjectName = "adminRadioButton";
            this.adminRadioButton.Text = "Admin";
            verticalLayout.AddWidget(this.adminRadioButton);
            this.memberRadioButton = new QRadioButton(this);
            this.memberRadioButton.ObjectName = "memberRadioButton";
            this.memberRadioButton.Text = "Member";
            verticalLayout.AddWidget(this.memberRadioButton);
            this.outcastRadioButton = new QRadioButton(this);
            this.outcastRadioButton.ObjectName = "outcastRadioButton";
            this.outcastRadioButton.Text = "Outcast (Banned)";
            verticalLayout.AddWidget(this.outcastRadioButton);
            this.noneRadioButton = new QRadioButton(this);
            this.noneRadioButton.ObjectName = "noneRadioButton";
            this.noneRadioButton.Text = "None";
            verticalLayout.AddWidget(this.noneRadioButton);
            QGridLayout gridLayout_2;
            gridLayout_2 = new QGridLayout();
            verticalLayout_2.AddLayout(gridLayout_2);
            this.reasonLineEdit = new QLineEdit(this);
            this.reasonLineEdit.ObjectName = "reasonLineEdit";
            gridLayout_2.AddWidget(this.reasonLineEdit, 0, 1, 1, 1);
            this.label = new QLabel(this);
            this.label.ObjectName = "label";
            this.label.Text = "Reason:";
            gridLayout_2.AddWidget(this.label, 0, 0, 1, 1);
            this.label_4 = new QLabel(this);
            this.label_4.ObjectName = "label_4";
            this.label_4.Text = "(optional)";
            gridLayout_2.AddWidget(this.label_4, 0, 2, 1, 1);
            this.buttonBox = new QDialogButtonBox(this);
            this.buttonBox.ObjectName = "buttonBox";
            this.buttonBox.Orientation = Qt.Orientation.Horizontal;
            this.buttonBox.StandardButtons = (global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Cancel") | global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Ok"));
            verticalLayout_2.AddWidget(this.buttonBox);
            QObject.Connect(buttonBox, Qt.SIGNAL("accepted()"), this, Qt.SLOT("accept()"));
            QObject.Connect(buttonBox, Qt.SIGNAL("rejected()"), this, Qt.SLOT("reject()"));
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
