// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using Qyoto;


public partial class PreferencesWindow : QWidget {
    
    protected QTabWidget tabWidget;
    
    protected QWidget tab;
    
    protected QListView listView;
    
    protected QFrame line;
    
    protected QWidget widget;
    
    protected QPushButton pushButton;
    
    protected QPushButton pushButton_2;
    
    protected QWidget tab_2;
    
    protected QDialogButtonBox buttonBox;
    
    protected void SetupUi() {
        base.ObjectName = "PreferencesWindow";
        this.Geometry = new QRect(0, 0, 400, 302);
        this.WindowTitle = "Synapse Preferences";
        QVBoxLayout verticalLayout;
        verticalLayout = new QVBoxLayout(this);
        verticalLayout.Margin = 6;
        this.tabWidget = new QTabWidget(this);
        this.tabWidget.ObjectName = "tabWidget";
        this.tabWidget.CurrentIndex = 0;
        verticalLayout.AddWidget(this.tabWidget);
        this.tab = new QWidget(this.tabWidget);
        this.tab.ObjectName = "tab";
        QVBoxLayout verticalLayout_2;
        verticalLayout_2 = new QVBoxLayout(this.tab);
        verticalLayout_2.Spacing = 0;
        verticalLayout_2.Margin = 0;
        this.listView = new QListView(this.tab);
        this.listView.ObjectName = "listView";
        this.listView.FrameShape = QFrame.Shape.NoFrame;
        verticalLayout_2.AddWidget(this.listView);
        this.line = new QFrame(this.tab);
        this.line.ObjectName = "line";
        this.line.FrameShape = QFrame.Shape.HLine;
        this.line.FrameShadow = QFrame.Shadow.Sunken;
        verticalLayout_2.AddWidget(this.line);
        this.widget = new QWidget(this.tab);
        this.widget.ObjectName = "widget";
        QHBoxLayout horizontalLayout;
        horizontalLayout = new QHBoxLayout(this.widget);
        horizontalLayout.Margin = 6;
        this.pushButton = new QPushButton(this.widget);
        this.pushButton.ObjectName = "pushButton";
        this.pushButton.Text = "Add Account";
        horizontalLayout.AddWidget(this.pushButton);
        this.pushButton_2 = new QPushButton(this.widget);
        this.pushButton_2.ObjectName = "pushButton_2";
        this.pushButton_2.Text = "Edit Account";
        horizontalLayout.AddWidget(this.pushButton_2);
        QSpacerItem horizontalSpacer;
        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum);
        horizontalLayout.AddItem(horizontalSpacer);
        verticalLayout_2.AddWidget(this.widget);
        this.tabWidget.AddTab(this.tab, "Accounts");
        this.tab_2 = new QWidget(this.tabWidget);
        this.tab_2.ObjectName = "tab_2";
        this.tabWidget.AddTab(this.tab_2, "General");
        this.buttonBox = new QDialogButtonBox(this);
        this.buttonBox.ObjectName = "buttonBox";
        this.buttonBox.Orientation = Qt.Orientation.Horizontal;
        this.buttonBox.StandardButtons = global::Qyoto.Qyoto.GetCPPEnumValue("QDialogButtonBox", "Close");
        verticalLayout.AddWidget(this.buttonBox);
        QMetaObject.ConnectSlotsByName(this);
    }
}
