// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient {
    using System;
    using Qyoto;
    
    
    public partial class ServiceBrowserWindow : QWidget {
        
        protected QWebView webView;
        
        protected void SetupUi() {
            base.ObjectName = "ServiceBrowserWindow";
            this.Geometry = new QRect(0, 0, 484, 401);
            this.WindowTitle = "XMPP Browser";
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this);
            verticalLayout.Spacing = 0;
            verticalLayout.Margin = 0;
            this.webView = new QWebView(this);
            this.webView.ObjectName = "webView";
            this.webView.Url = new QUrl("about:blank");
            verticalLayout.AddWidget(this.webView);
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
