// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Synapse.QtClient.Widgets {
    using System;
    using Qyoto;
    
    
    public partial class WebIdentityConfiguratorWidget : QWidget {
        
        protected QLabel iconLabel;
        
        protected QLabel nameLabel;
        
        protected QWidget widget;
        
        protected QPushButton configureButton;
        
        protected QFrame line;
        
        protected void SetupUi() {
            base.ObjectName = "WebIdentityConfiguratorWidget";
            this.Geometry = new QRect(0, 0, 540, 61);
            this.WindowTitle = "WebIdentityConfiguratorWidget";
            QVBoxLayout verticalLayout_2;
            verticalLayout_2 = new QVBoxLayout(this);
            verticalLayout_2.Spacing = 6;
            verticalLayout_2.Margin = 0;
            QHBoxLayout horizontalLayout;
            horizontalLayout = new QHBoxLayout();
            verticalLayout_2.AddLayout(horizontalLayout);
            horizontalLayout.Spacing = 6;
            this.iconLabel = new QLabel(this);
            this.iconLabel.ObjectName = "iconLabel";
            this.iconLabel.MinimumSize = new QSize(48, 0);
            this.iconLabel.Text = "";
            horizontalLayout.AddWidget(this.iconLabel);
            this.nameLabel = new QLabel(this);
            this.nameLabel.ObjectName = "nameLabel";
            QSizePolicy nameLabel_sizePolicy;
            nameLabel_sizePolicy = new QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred);
            nameLabel_sizePolicy.SetVerticalStretch(0);
            nameLabel_sizePolicy.SetHorizontalStretch(0);
            nameLabel_sizePolicy.SetHeightForWidth(this.nameLabel.SizePolicy.HasHeightForWidth());
            this.nameLabel.SizePolicy = nameLabel_sizePolicy;
            this.nameLabel.Text = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Bitstream Vera Sans'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Addin Name</span></p>\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><span style=\" font-weight:400;\">Addin description.</span></p></body></html>";
            this.nameLabel.Alignment = ((global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignLeading") | global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignLeft")) | global::Qyoto.Qyoto.GetCPPEnumValue("Qt", "AlignVCenter"));
            this.nameLabel.WordWrap = true;
            horizontalLayout.AddWidget(this.nameLabel);
            this.widget = new QWidget(this);
            this.widget.ObjectName = "widget";
            QVBoxLayout verticalLayout;
            verticalLayout = new QVBoxLayout(this.widget);
            verticalLayout.Margin = 0;
            this.configureButton = new QPushButton(this.widget);
            this.configureButton.ObjectName = "configureButton";
            this.configureButton.Text = "Configure...";
            verticalLayout.AddWidget(this.configureButton);
            horizontalLayout.AddWidget(this.widget);
            this.line = new QFrame(this);
            this.line.ObjectName = "line";
            this.line.FrameShape = QFrame.Shape.HLine;
            this.line.FrameShadow = QFrame.Shadow.Sunken;
            verticalLayout_2.AddWidget(this.line);
            QMetaObject.ConnectSlotsByName(this);
        }
    }
}
